import { Geist, Geist_Mono } from "next/font/google";
import Layout from "../components/layout/Layout";
import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BotoCar",
  description: "Generated by Car Sales Site",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Layout className={`${geistSans.variable} ${geistMono.variable}`}>
          {children}
        </Layout>
      </body>
    </html>
  );
}
